### ISSUE TITLE
Error with `chat_claude()` when giving local data URI to `elmer::content_image_url()` 

### ISSUE THREAD

**Issue by cpsievert** [hadley/elmer#110]
Currently `elmer::content_image_url()` always returns `ContentImageRemote()`, even though (at least from the docs) inline images are also supported here. As a result, you currently get an error with Claude about it not supporting remote images. I think it would make sense for `elmer::content_image_url()` to return `ContentImageInline()` instead when a URI gets passed?

**Comment by hadley** [comment]
You mean it would read the remote url and insert the raw data into a `ContentImageInline()`?

**Comment by cpsievert** [comment]
No I mean like `content_image_url("data:image/png;base64,...")` should return a `ContentImageInline()`

**Comment by hadley** [comment]
Oh hmmmm, I forgot that you could supply data urls here. Your suggestion makes more sense now 😄
