### ISSUE TITLE
Error when connecting to ollama server (not local)

### ISSUE THREAD

**Issue by davidmeza1** [hadley/elmer#128]
I can use my local instance of ollama to return responses using the chat_ollama function. However when I change the base_url to a server we set up I get the error.
I have tested the server connection via my terminal, successfully getting a response.
 I am running R 4.4.0 on MacBook Pro Sonoma 14.7
```
Error in `req_perform_connection()`:
! Failed to parse error body with method defined in `req_error()`.
Caused by error in `resp_body_json()`:
! Unexpected content type "text/plain".
• Expecting type "application/json" or suffix "json".

```
Here is the code I used, chat1 works, chat2 fails
```
library(elmer)

chat_msg = c("What preceeding languages most influenced R?")
chat1 <- chat_ollama(
  model = "mistral:instruct",
  system_prompt = "You are a friendly but terse assistant.",
  echo = TRUE
)
chat2 <- chat_ollama(
  base_url = "http://131.xxx.xxx.xxx:443/api/generate",
  model = "mistral:instruct",
  system_prompt = "You are a friendly but terse assistant.",
  echo = TRUE
)
chat1$chat(chat_msg)
chat2$chat(chat_msg)
```

**Comment by hadley** [comment]
Can you please show me what this reutrns for you?

```R
library(httr2)
resp <- last_response()
cat(resp_body_string(resp))
```

**Comment by davidmeza1** [comment]
Apologies, I had to leave on travel. Turns out we were using the wrong endpoint.  Changing the base url to 
base_url = "http://131.xxx.xxx.xxx:443/v1" worked. This can be closed.

**Comment by hadley** [comment]
Ah yeah, it's unfortunately that ollama doesn't give better errors if you use the wrong url 😞

**Comment by hadley** [comment]
I made the error a bit clearer:

```R
chat_ollama(base_url = "http://localhost:11434", model = "mistral")$chat("Hi")
#> Error in `req_perform()`:
#> ! HTTP 404 Not Found.
```
