### ISSUE TITLE
Consider not saving chat history

### ISSUE THREAD

**Issue by JamesHWade** [hadley/elmer#130]
This is a similar thought to #29, but maybe a bit easier to implement. In some cases, we may want to make repeated API calls without saving the history for each call. An example is Edgar Ruiz's [mall](https://github.com/edgararuiz/mall) package.

Preserving the usage monitoring but removing the history would be nice. What about adding a `save_history` param to `chat()`?

**Comment by hadley** [comment]
For now, I'd recommend setting up a base chat object and then calling `$clone()` before you start chatting. I'm not sure what this interface will look like long term, but it's also likely to be connected to caching (#107)

**Comment by DavZim** [comment]
It would be great if we have something like this, that would make the user/developer experience a lot nicer imo:

```R
library(ellmer)

# maybe save_chat or so is a better name ...
chat <- chat_openai(..., ephemeral = TRUE)

chat$set_ephemeral(TRUE)
```
