### ISSUE TITLE
save mesages as a specific class

### ISSUE THREAD

**Issue by topepo** [hadley/elmer#44]
It would be helpful to class the list with each message. From there, we can add `format()`, `as_tibble()`, and other methods to facilitate programming against the elmer api.

**Comment by jcheng5** [comment]
+1, and maybe classing the list of messages as well. I can imagine wanting to pretty-print subsets of the message history.

**Comment by hadley** [comment]
Now have the idea of Turns: https://hadley.github.io/elmer/reference/Turn.html
