### ISSUE TITLE
use on.exit() for chats

### ISSUE THREAD

**Issue by topepo** [hadley/elmer#46]
Since users press Ctrl+C to quit, programming against the chat (e.g., to save or format the chat) is not straightforward. 

Can we return some elements of the chat once it is finished? I'm currently using `on.exit()` to write out `.Last.chat.result`

**Comment by hadley** [comment]
Can give a bit more detail about the scenario you're thinking of

**Comment by topepo** [comment]
For a chat inside an R session, if people ask how to do specific things in tidymodels, I'm not sure how we would recover the history. Here's my [currrent method](https://github.com/topepo/sommelier/blob/main/R/tm_chat.R#L19). Ctrl-C kills the chat session and the function that called it.

**Comment by hadley** [comment]
Oooh this is specifically about console.  I think you could do this:

```R
tm_chat <- function(model = "gpt-4o-mini") {
  # TODO This needs a better name
  # TODO Use anthropic instead
  chat <- elmer::new_chat_openai(
    model = model,
    system_prompt = get_instructions(),
    echo = TRUE
  )

  tryCatch(
    chat$console(),
    interrupt = function(cnd) NULL
  )
  
  invisible(chat)
}```
