### ISSUE TITLE
Example documentation for Azure hosted OpenAI models

### ISSUE THREAD

**Issue by iainwallacebms** [hadley/elmer#76]
This is a very exciting package! Would it be possible to get an example of how to set up elmer with an Azure hosted end point or an example on how to debug the connection?

I was able to use our internal end point for the [py-sidebot](https://github.com/jcheng5/py-sidebot) example using the [LiteLLM directions](https://docs.litellm.ai/docs/providers/azure) but I get an error when I try to do similarly with elmer

     chat<-elmer::new_chat_openai(api_key = API_KEy,
                           base_url = INTERNAL_BASE_URL,
                           model = "gpt-4o-global")

The error I get is 

        "Error in `req_perform()`:
        ! Failed to parse error body with method defined in `req_error()`. 
        Caused by error in `resp_body_json()`:
        ! Unexpected content type "text/html".
        • Expecting type "application/json" or suffix "json"."

We had a similar issue using the chatstream package - https://github.com/wch/chatstream/issues/8

**Comment by hadley** [comment]
Can you share your `INTERNAL_BASE_URL`? That error suggests an HTML error because you're not actually hitting the API.

**Comment by iainwallacebms** [comment]
Sure - https://bms-openai-services-westus3-1-nonprod.azu.bms.com 
It is the same base URL that I use in python

**Comment by hadley** [comment]
Can you try using `https://bms-openai-services-westus3-1-nonprod.azu.bms.com/v1`?   

If that doesn't work, you might need to do a bit of experimentation to figure out what url gives you the same error as https://models.inference.ai.azure.com. 

I wonder if there's some way to see the request that liteLLM is sending?

**Comment by iainwallacebms** [comment]
Thanks. I get the same error with that url. Is there a way of seeing what the request elmer is sending out?

**Comment by hadley** [comment]
You can use `httr2::last_request()` and `httr2::last_response()` to see the failing request and response. That should allow you to look at the html, which might be useful.

**Comment by iainwallacebms** [comment]
This is the post request sent by LiteLLM:

     POST Request Sent from LiteLLM:
     curl -X POST \
     https://bms-openai-services-northcentralus-1-nonprod.azu.bms.com/
     \
    -H 'api_key: *****' -H 'azure_ad_token: *****' \
    -d '{'model': 'gpt-4o-global', 'messages': [{'content': 'Hello, how are you?', 'role': 'user'}], 'extra_body': {}}'

We think the azure_ad_token is generated by this code snippet but am unsure if we can recreate it in R.

       from litellm import completion

       from azure.identity import DefaultAzureCredential, get_bearer_token_provider

       token_provider = get_bearer_token_provider(DefaultAzureCredential(),
       "
       [https://cognitiveservices.azure.com/.default"](https://cognitiveservices.azure.com/.default%22)
       )


        response = completion(

        model =
        "azure/<your deployment name>"
      ,             # model = azure/<your deployment name> 

        api_base =
       ""
      ,                                      # azure api base

      api_version =
      ""
       ,                                   # azure api version

        azure_ad_token_provider=token_provider

        messages = [{
        "role"
       :
     "user"
     ,
     "content"
     :
     "good morning"
      }],

     )

**Comment by iainwallacebms** [comment]
Sure:  
       cat(httr2::resp_body_string(httr2::last_response()))
       <html>
       <head><title>500 Internal Server Error</title></head>
       <body>
       <center><h1>500 Internal Server Error</h1></center>
       <hr><center>nginx</center>
       </body>
       </html>


Incase it is useful, this is the basic way of connecting through the official python package that works for my endpoint, courtesy of https://elanthirayan.medium.com/using-azure-openai-with-python-a-step-by-step-guide-415d5850169b

     import os
     from openai import AzureOpenAI

     endpoint = "Your_Endpoint"  # https://xyz.azure.com/
     key = "Your_Key"  # Your API key
     model_name = "gpt-4o"  # Your model name

    client = AzureOpenAI(
         azure_endpoint=endpoint,
         api_version="2024-02-01",
         api_key=key
     )

      completion = client.chat.completions.create(
      model=model_name,
      messages=[
         {
             "role": "user",
             "content": "What is AI?",  # Your question can go here
         },
     ],
     )

     print(completion.choices[0].message.content)

I will update if I can figure out the actual post command that gets sent from this package

**Comment by hadley** [comment]
Hmmmm. We may need to add a provider specifically for azure.

**Comment by iainwallacebms** [comment]
In case it is useful, this is a working curl command:

curl --location --request POST 'BASE_URL/openai/deployments/gpt-4o-global/chat/completions?api-version=2024-02-01' \
--header 'api-key: API_KEY' \
--header 'Content-Type: application/json' \
--data '{
  "messages": [
    {
      "role": "system",
      "content": "you'\''re a helpful assistant that talks like a pirate"
    },
    {
      "role": "user",
      "content": "can you tell me how to care for a parrot?"
    }
  ]
}'

**Comment by hadley** [comment]
In that case using `https://bms-openai-services-westus3-1-nonprod.azu.bms.com/openai/deployments/gpt-4o-global/` as a base url should work.

**Comment by iainwallacebms** [comment]
Unfortunately that didn't work - I think we need the api_version at the end of the call

**Comment by hadley** [comment]
Yeah, and the model goes in the url, not the request body.

**Comment by hadley** [comment]
Please give #102 a go. It works for me for the Azure model that I just created and blindly copy and pasted 😄

**Comment by iainwallacebms** [comment]
It worked for me! Thanks, this will be so useful.

**Comment by trangdata** [comment]
Working for me as well! Thanks, Hadley!

``` r
library(elmer)
chat <- chat_azure(
  api_version = "2024-02-01",
  endpoint = "https://bms-openai-services-westus3-1-nonprod.azu.bms.com/",
  deployment_id = "gpt-4o-global",
  system_prompt = "You are a friendly but terse assistant.",
  echo = TRUE
)
chat$chat("What is the capital of France?")
#> The capital of France is Paris.
```

<sup>Created on 2024-10-08 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
